config/routes.rb
RailsProject::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "show/user/:id" => "users#show_user", :as => "show_user"
  get "tasks/:id/:status" => "tasks#change_status", :as => "task_change"
  get "modal/:id" => "tasks#modal"
  get "show_task/side_bar/:task_id" => "tasks#side_bar_task"
  get "edit_tasks" => "tasks#show_user_tasks", :as => "edit_tasks"
  get "remove/:task_id/:username" => "users#remove_user_from_task"
  get "removefile/:file_id" => "tasks#remove_file_from_task"
  root 'users#index'

  resources :users do
    resources :tasks
  end
  resources :sessions

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sharedtasks
  has_many :tasks, :through => :sharedtasks
  has_attached_file :avatar, :styles => {:medium => "250x250"}
  attr_accessor :password	

  before_save :encrypt_password
  validates_attachment_content_type :avatar, :content_type => /.(?:jpe?g|png|gif)$/
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email, :username
  validates_uniqueness_of :email, :username

  def self.authenticate(login,password)
    user = find_by_email(login)
    user = find_by_username(login) unless user
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:search]
      @tasks = current_user.tasks.where("taskname LIKE ? OR description LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%")
      if @tasks.first
        return
      else
        @tasks = nil
      end
    else
      @no_query = true
    end
  end

  def new
  	@user = User.new
  end

  def show_user
    @user = User.find_by_id(params[:id])
  end

  def create
  	@user = User.new(user_params) 
  	if @user.save
      session[:user_id] = @user.id
  	  redirect_to user_path(@user.id), :notice => "sighned up"
  	else
  	  flash.now[:alert] = "errors"
  	  render "new"
  	end
  end

  def update
    flash = current_user.update_attributes(user_params) ? {:notice => "Updated"} : {:notice => current_user.errors.full_messages.to_sentence}
    redirect_to :back, flash
  end

  def show
    @tasks = current_user.tasks
                         .order("#{sort_column} #{sort_direction}")
                         .paginate(:per_page => 5, :page => params[:page])
  end

  def remove_user_from_task
    @user_to_remove = find_user(params[:username])   
    @query = Sharedtask.where("user_id = ? AND task_id = ?", @user_to_remove, params[:task_id]).first.destroy
    render :json => @query and return
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_usertasks.html.haml
%table.table
  %tr
    %td #
    %td.sort= sortable "taskname"
    %td.sort= sortable "description"
    %td.sort= sortable "status"
    %td Action
  - @tasks.each_with_index do |task, index|
    %tr
      %td= index + 1
      %td= link_to "#{task.taskname}", edit_user_task_path(current_user.id, task.id)
      %td= task.description
      %td= task.status
      %td= link_to "Delete", user_task_path(current_user.id, task.id), method: "delete", confirm: "Are you sure?"
= will_paginate @tasks

app/views/users/edit.html.haml
%div
  %p
    %h4
      #{current_user.username}
    = image_tag current_user.avatar.url(:medium)
  %p
    Email : #{current_user.email}
  %p
    Created at : #{current_user.created_at}
%button{id: "update_profile"}
  Change you data
%div.hide{id: "update_form"}  
  = form_for current_user, :html => {:multipart => true} do |f|
    %p
      = f.label :userName
      = f.text_field :username
    %p
      = f.label :email
      = f.text_field :email
    %p
      = f.label :password
      = f.password_field :password
    %p
      = f.label :password_confirmation
      = f.password_field :password_confirmation
    %p
      = f.label :avatar
      = f.file_field :avatar
    %p.button= f.submit

app/views/users/index.html.haml
- if @tasks
  %table.table
    %thead
      %tr
        %td #
        %td Taskname
        %td Description
        %td Usersintask
        %td Status
    %tbody
      - @tasks.each_with_index do |task, index|
        %tr
          %td= index + 1
          %td= link_to "#{task.taskname}", edit_user_task_path(current_user.id, task.id)
          %td= task.description
          %td 
            - task.usersintask.each do |user| 
              = link_to user.username + " ", show_user_path(user.id)
          %td= task.status
- elsif !@no_query
  %span
    Nothing found for : #{params[:search]}

app/views/users/new.html.haml
%h1 Sign up
= form_for @user, :html => {:multipart => true} do |f|
  - if @user.errors.any?
    .error_message
      %h2 Form is invalid>
      %ul
        - for message in @user.errors.full_messages
          %li= message
  %p
    = f.label :userName
    = f.text_field :username
  %p
    = f.label :email
    = f.text_field :email
  %p
    = f.label :password
    = f.password_field :password
  %p
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  %p
    = f.label :avatar
    = f.file_field :avatar
  %p.button= f.submit

app/views/users/show.html.haml
#main_nav
  %h1
    Welcome #{current_user.username}
#tasks
  = render 'usertasks'

app/views/users/show.js.haml
$("#tasks").html("#{escape_javascript(render('usertasks'))}")

app/views/users/show_user.html.haml
%div
  %h4
    #{@user.username}
  = image_tag @user.avatar.url(:medium)
  %p
    Email : #{@user.email}
  %p
    Created at : #{@user.created_at}