config/routes.rb
RailsProject::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "show/user/:id" => "users#show_user", :as => "show_user"
  get "tasks/:id/:status" => "tasks#change_status", :as => "task_change"
  get "modal/:id" => "tasks#modal"
  get "show_task/side_bar/:task_id" => "tasks#side_bar_task"
  get "edit_tasks" => "tasks#show_user_tasks", :as => "edit_tasks"
  get "remove/:task_id/:username" => "users#remove_user_from_task"
  get "removefile/:file_id" => "tasks#remove_file_from_task"
  root 'users#index'

  resources :users do
    resources :tasks
  end
  resources :sessions

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RailsProject
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top.navbar-inverse
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => root_url} Rails APP
          .nav-collapse
            %ul.nav
              - if current_user
                %li= link_to "Home page", user_path(current_user.id)
                %li= link_to "Show all tasks", user_tasks_path(current_user.id)
                %li= link_to "Edit your tasks", edit_tasks_path
                %li= link_to "Add task", new_user_task_path(current_user.id)
                %li= link_to "My profile", edit_user_path(current_user.id)
                = form_tag  root_url, :class => "navbar-search", :method => "GET" do
                  = text_field_tag :search, params[:search], :class => "search-query", :placeholder => "Search"
                %li.pull-right= link_to "Log Out", log_out_path
              - else
                %li= link_to "Sign up", sign_up_path
                %li= link_to "Log in", log_in_path
    .container
      .row
        .span10
          - flash.each do |name, msg|
            = content_tag :div, msg, :id => "flash_#{name}"
          = yield
        .span2
          %h2 Task helper
          %p.task_info